### ISSUE TITLE
how do i implement custom metrics with this? can you help guide?

### ISSUE THREAD

**Issue by malikal-hh** [rakutentech/passenger-go-exporter#41]
#### Environment (If your question is related to environment):

**Kubernetes Version:**

```bash
```

**Promethues Version:**

**Passenger Version:**

**Passenger Go Exporter:**

**Comment by h-r-k-matsumoto** [comment]
Hi @malikal-hh,
Thank you for raising an issue and sorry for late.
Could you share what metrics you want to customize?
such as...

- add metrics providing Passenger?
- modify calculation or data type of Prometheus?
